import math

# User interface changeable settings for the game
RESOLUTION = WIDTH, HEIGHT = 1200, 700
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FRAMES = 60

PLAYER_POSITION = 4, 4
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.002
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
